version: '3.8'

services:
  web:
    build: .
    command: gunicorn two_factor_auth.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/django-two-factor-auth-app
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    environment:
      - SECRET_KEY="${SECRET_KEY}"
      - DEBUG="${DEBUG}"
  db:
    image: postgres
    container_name: db
    networks:
      - djangonetwork
    networks:
      - djangonetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
networks:
  djangonetwork:
    driver: bridge